<a href="https://colab.research.google.com/github/AkshitBahl/AI-ML_Testing_1/blob/main/SmartBridge_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

AI-ML using Python Data Science

ASSIGNMENT - 1

AKSHIT BAHL | 21BIT0012 | Vellore Campus | B.Tech. | Information Technology

First we will import the necessary Python Libraries.
1. Pandas - for manipulating data
2. NumPy - to deal with arrays

In [13]:
import pandas as pd
import numpy as np

Now, we will make a dictionary of some random data of Laptops, in which we will insert 5 observations with its 5 features.

In [9]:
d={"name":["ASUS Vivobook Pro 15","HP Laptop 15","Dell G15-5520","Samsung Galaxy Book2(NP750)","Lenovo Ideapad Slim 3"],"ram":[16,8,8,4,np.nan],"rom":[256,512,np.nan,1024,256],"screen_size":[14.0,15.6,13.8,np.nan,15.6],"price":[65990,49980,57490,61000,45500]}
d

{'name': ['ASUS Vivobook Pro 15',
  'HP Laptop 15',
  'Dell G15-5520',
  'Samsung Galaxy Book2(NP750)',
  'Lenovo Ideapad Slim 3'],
 'ram': [16, 8, 8, 4, nan],
 'rom': [256, 512, nan, 1024, 256],
 'screen_size': [14.0, 15.6, 13.8, nan, 15.6],
 'price': [65990, 49980, 57490, 61000, 45500]}

Above shown is our dictionary with randome values, along with some 'null' values.

Now, next step is to convert this dictionary into a DataFrame model with the help of Pandas library of Python.

In [10]:
df=pd.DataFrame(d)
df

                          name   ram     rom  screen_size  price
0         ASUS Vivobook Pro 15  16.0   256.0         14.0  65990
1                 HP Laptop 15   8.0   512.0         15.6  49980
2                Dell G15-5520   8.0     NaN         13.8  57490
3  Samsung Galaxy Book2(NP750)   4.0  1024.0          NaN  61000
4        Lenovo Ideapad Slim 3   NaN   256.0         15.6  45500

NOTE:

If we want to insert random floating point values using numPy into our Pandas DataFrame, then we can do it using the following code:

In [12]:
num_rows = 4
num_columns = 4
df2 = pd.DataFrame(index=range(num_rows), columns=range(num_columns))

# Generate random values using NumPy and assign them to the DataFrame
for i in range(num_rows):
    for j in range(num_columns):
        df2.at[i, j] = np.random.random()

df2

          0         1         2         3
0  0.504475  0.982481  0.873438  0.481967
1  0.524035  0.533497  0.706109  0.350247
2  0.956766   0.64919  0.376559  0.357406
3  0.636732  0.215194  0.022618  0.746319

So TASK - 1 COMPLETED !

Now Task - 2 is to rename all the columns of our DataFrame to "Random Value 1", "Random Value 2", "Random Value 3", "Random Value 4" and "Random Value 5".

AKSHIT BAHL | 21BIT0012 | Vellore Campus | B.Tech. | Information Technology

In [11]:
df.columns=("Random Value 1","Random Value 2","Random Value 3","Random Value 4","Random Value 5")
df

,Random Value 1,Random Value 2,Random Value 3,Random Value 4,Random Value 5
0,ASUS Vivobook Pro 15,16.0,256.0,14.0,65990
1,HP Laptop 15,8.0,512.0,15.6,49980
2,Dell G15-5520,8.0,NaN,13.8,57490
3,Samsung Galaxy Book2(NP750),4.0,1024.0,NaN,61000
4,Lenovo Ideapad Slim 3,NaN,256.0,15.6,45500

SO TASK - 2 IS COMPLETED !

Now, for task - 3, we have to find the descriptive statistics of the 'df' DataFrame.

We will do it using the '.describe()' function.

AKSHIT BAHL | 21BIT0012 | Vellore Campus | B.Tech. | Information Technology

In [14]:
df.describe()

       Random Value 2  Random Value 3  Random Value 4  Random Value 5
count        4.000000        4.000000        4.000000        5.000000
mean         9.000000      512.000000       14.750000    55992.000000
std          5.033223      362.038672        0.984886     8269.073104
min          4.000000      256.000000       13.800000    45500.000000
25%          7.000000      256.000000       13.950000    49980.000000
50%          8.000000      384.000000       14.800000    57490.000000
75%         10.000000      640.000000       15.600000    61000.000000
max         16.000000     1024.000000       15.600000    65990.000000

SO TASK - 3 IS COMPLETED !

Now, for task - 4, we have to check if there are any null values present in our DataFrame, and then find the datatype of the columns.

AKSHIT BAHL | 21BIT0012 | Vellore Campus | B.Tech. | Information Technology

In [15]:
df.isnull().any()

Random Value 1    False
Random Value 2     True
Random Value 3     True
Random Value 4     True
Random Value 5    False
dtype: bool

This shows that the columns 2, 3 and 4 have null values in it.

There is also one another way to find null values in a column:

In [16]:
df.isnull().sum()

Random Value 1    0
Random Value 2    1
Random Value 3    1
Random Value 4    1
Random Value 5    0
dtype: int64

Now, to find the data types of the columns:

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random Value 1  5 non-null      object
 1   Random Value 2  4 non-null      float64
 2   Random Value 3  4 non-null      float64
 3   Random Value 4  4 non-null      float64
 4   Random Value 5  5 non-null      int64
dtypes: float64(3), int64(1), object(1)
memory usage: 328.0+ bytes

SO TASK - 4 IS COMPLETED !

Now, for task - 5, we have to display the 'random value 2' and 'random value 3' columns with 'loc' and 'iloc' methods.

AKSHIT BAHL | 21BIT0012 | Vellore Campus | B.Tech. | Information Technology

In [20]:
df.loc[:,'Random Value 2':'Random Value 3']

   Random Value 2  Random Value 3
0            16.0           256.0
1             8.0           512.0
2             8.0             NaN
3             4.0          1024.0
4             NaN           256.0

Now, with 'iloc' method:

In [22]:
df.iloc[:,1:3]

   Random Value 2  Random Value 3
0            16.0           256.0
1             8.0           512.0
2             8.0             NaN
3             4.0          1024.0
4             NaN           256.0

SO TASK - 5 IS COMPLETED !



AKSHIT BAHL | 21BIT0012 | Vellore Campus | B.Tech. | Information Technology